--1.Find Departments with Average Salary Greater than a Certain Amount

SELECT D.DEPT_NAME
FROM EMPLOYEES E
INNER JOIN
DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPT_ID
GROUP BY D.DEPT_NAME
HAVING AVG(E.SALARY)>50000

--2.List Employees with Salaries Above the Department Average and Working on More Than One Project

SELECT E.EMP_ID
,E.FULL_NAME
,E.SALARY
,E.DEPARTMENT_ID
FROM EMPLOYEES E
INNER JOIN 
(
    SELECT DEPARTMENT_ID
	,AVG(SALARY) AS AVG_SALARY
    FROM EMPLOYEES
    GROUP BY DEPARTMENT_ID
) AVG_DEPT 
ON E.DEPARTMENT_ID = AVG_DEPT.DEPARTMENT_ID
AND E.SALARY > AVG_DEPT.AVG_SALARY
WHERE (
		SELECT COUNT(*)
		FROM EMPLOYEE_PROJECTS EP
		WHERE EP.EMP_ID = E.EMP_ID
	) > 1;

--3.Find Employees with the Highest Salary in Each Department and List Their Projects

SELECT E.EMP_ID
,E.FULL_NAME
,EP.PROJECT_ID
,P.PROJECT_NAME
FROM EMPLOYEES E
INNER JOIN 
(
    SELECT DEPARTMENT_ID
	,MAX(SALARY) AS MAX_SALARY
    FROM EMPLOYEES
    GROUP BY DEPARTMENT_ID
) MAX_SAL 
ON E.DEPARTMENT_ID = MAX_SAL.DEPARTMENT_ID
AND E.SALARY = MAX_SAL.MAX_SALARY
INNER JOIN
EMPLOYEE_PROJECTS EP
ON E.EMP_ID = EP.EMP_ID
INNER JOIN
PROJECTS P
ON EP.PROJECT_ID = P.PROJECT_ID;