SELECT FF.ID AS SRC_EMP_ID
,FF.NAME AS SRC_NAME
,FF.DATE_OF_BIRTH AS SRC_DOB
,FF.SALARY AS SRC_SALARY
,FF.DEPARTMENT_ID AS SRC_DEPARTMENT_ID
,E.EMP_ID AS TGT_EMP_ID
,E.FULL_NAME AS TGT_NAME
,E.DOB AS TGT_DOB
,E.SALARY AS TGT_SALARY
,E.DEPARTMENT_ID AS TGT_DEPARTMENT_ID
,D.DEPT_NAME AS TGT_DEPT_NAME
FROM SOURCE_FLAT_FILE FF
LEFT JOIN
EMPLOYEES E
ON FF.ID = E.EMP_ID
AND FF.NAME = E.FULL_NAME
AND FF.DATE_OF_BIRTH = E.DOB
AND FF.SALARY = E.SALARY
AND FF.DEPARTMENT_ID = E.DEPARTMENT_ID
LEFT JOIN
DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPT_ID
WHERE E.EMP_ID IS NULL
OR (E.DEPARTMENT_ID IS NOT NULL AND D.DEPT_NAME IS NULL);